In [1]:
import pandas as pd

path = "price_availability.csv"
df_prices = pd.read_csv(path, sep=";")
df_prices.head()

,listing_id,day,created,available,local_currency,local_price,min_nights
0,9810829,2018-12-08,2018-09-27 06:14:10.000+0000,True,EUR,160,1
1,9810829,2018-12-08,2018-09-26 19:34:02.000+0000,True,EUR,160,1
2,20897010,2018-12-09,2018-09-27 10:38:57.000+0000,True,EUR,172,2
3,20897010,2018-12-09,2018-09-27 06:10:27.000+0000,True,EUR,172,2
4,20897010,2018-12-09,2018-09-26 19:30:25.000+0000,True,EUR,172,2

In [2]:
path2 = "listings_final.csv"
df_listing = pd.read_csv(path2, sep=";")
df_listing.head()

,Unnamed: 0,listing_id,name,type,city,neighborhood,latitude,longitude,person_capacity,beds,bedrooms,bathrooms,is_rebookable,is_new_listing,is_fully_refundable,is_host_highly_rated,is_business_travel_ready,pricing_weekly_factor,pricing_monthly_factor
0,0,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,2.0,False,True,True,False,False,1.00,1.00
1,1,661961,studio PARIS PLACE EDITH PIAF 75020,entire_home,Paris,NaN,48.867284,2.403255,2,1,1,1.0,False,False,True,True,False,0.88,0.69
2,2,1261705,chambre privée à louer @ paris oberkampf,private_room,Paris,NaN,48.867894,2.375897,1,1,1,1.0,False,False,True,True,False,1.00,1.00
3,3,1318834,Appartement au coeur du Marais,entire_home,Paris,République,48.870370,2.358510,3,2,2,1.0,False,False,True,False,False,0.82,0.48
4,4,1677091,Lovely & Quiet flat,entire_home,Paris,Buttes-Chaumont - Belleville,48.874149,2.373700,2,1,1,1.0,False,False,True,True,False,0.95,0.90

In [3]:
df_prices["local_price"].isna().sum()

0

In [4]:
del df_listing["Unnamed: 0"]
#df_listing

In [5]:
df_listing.groupby(['listing_id']).mean()
df_merged = pd.merge(df_listing, df_prices, on='listing_id')
#df_merged

In [6]:
mean_prices = df_merged.groupby(['listing_id'])["local_price"].mean()

In [7]:
df_prices = pd.merge(df_prices, mean_prices, on='listing_id')

In [8]:
df = pd.merge(df_listing, df_prices, on='listing_id')
df

,listing_id,name,type,city,neighborhood,latitude,longitude,person_capacity,beds,bedrooms,...,is_business_travel_ready,pricing_weekly_factor,pricing_monthly_factor,day,created,available,local_currency,local_price_x,min_nights,local_price_y
0,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-10-28,2018-09-27 10:40:22.000+0000,False,EUR,47,1,45.948454
1,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-10-28,2018-09-27 06:06:07.000+0000,False,EUR,47,1,45.948454
2,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-10-28,2018-09-26 19:31:53.000+0000,False,EUR,47,1,45.948454
3,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-09-01,2018-09-27 10:40:22.000+0000,True,EUR,47,1,45.948454
4,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-09-01,2018-09-27 06:06:07.000+0000,True,EUR,47,1,45.948454
5,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-09-01,2018-09-26 19:31:53.000+0000,True,EUR,47,1,45.948454
6,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-11-29,2018-09-27 10:40:22.000+0000,False,EUR,47,1,45.948454
7,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-11-29,2018-09-27 06:06:07.000+0000,False,EUR,47,1,45.948454
8,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-11-29,2018-09-26 19:31:53.000+0000,False,EUR,47,1,45.948454
9,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-09-23,2018-09-27 10:40:22.000+0000,True,EUR,47,1,45.948454
10,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-09-23,2018-09-27 06:06:07.000+0000,True,EUR,47,1,45.948454
11,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-09-23,2018-09-26 19:31:53.000+0000,True,EUR,47,1,45.948454
12,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-11-06,2018-09-27 10:40:22.000+0000,False,EUR,47,1,45.948454
13,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-11-06,2018-09-27 06:06:07.000+0000,False,EUR,47,1,45.948454
14,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-11-06,2018-09-26 19:31:53.000+0000,False,EUR,47,1,45.948454
15,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-10-02,2018-09-27 10:40:22.000+0000,False,EUR,41,1,45.948454
16,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-10-02,2018-09-27 06:06:07.000+0000,False,EUR,41,1,45.948454
17,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-10-02,2018-09-26 19:31:53.000+0000,False,EUR,41,1,45.948454
18,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-09-29,2018-09-27 10:40:22.000+0000,False,EUR,47,1,45.948454
19,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-09-29,2018-09-27 06:06:07.000+0000,False,EUR,47,1,45.948454
20,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-09-29,2018-09-26 19:31:53.000+0000,False,EUR,47,1,45.948454
21,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-10-07,2018-09-27 10:40:22.000+0000,False,EUR,47,1,45.948454
22,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-10-07,2018-09-27 06:06:07.000+0000,False,EUR,47,1,45.948454
23,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-10-07,2018-09-26 19:31:53.000+0000,False,EUR,47,1,45.948454
24,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-11-21,2018-09-27 10:40:22.000+0000,False,EUR,47,1,45.948454
25,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-11-21,2018-09-27 06:06:07.000+0000,False,EUR,47,1,45.948454
26,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-11-21,2018-09-26 19:31:53.000+0000,False,EUR,47,1,45.948454
27,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-09-06,2018-09-27 10:40:22.000+0000,True,EUR,47,1,45.948454
28,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-09-06,2018-09-27 06:06:07.000+0000,True,EUR,47,1,45.948454
29,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,...,False,1.0,1.0,2018-09-06,2018-09-26 19:31:53.000+0000,True,EUR,47,1,45.948454
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402586,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-09-04,2018-09-26 19:36:28.000+0000,True,EUR,39,1,39.503937
402587,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-11-27,2018-09-27 10:50:12.000+0000,True,EUR,40,1,39.503937
402588,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-11-27,2018-09-27 06:16:22.000+0000,True,EUR,40,1,39.503937
402589,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-11-27,2018-09-26 19:36:28.000+0000,True,EUR,39,1,39.503937
402590,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-10-21,2018-09-27 10:50:12.000+0000,True,EUR,41,1,39.503937
402591,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-10-21,2018-09-27 06:16:22.000+0000,True,EUR,41,1,39.503937
402592,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-10-21,2018-09-26 19:36:28.000+0000,True,EUR,39,1,39.503937
402593,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-09-06,2018-09-27 10:50:12.000+0000,True,EUR,39,1,39.503937
402594,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-09-06,2018-09-27 06:16:22.000+0000,True,EUR,39,1,39.503937
402595,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-09-06,2018-09-26 19:36:28.000+0000,True,EUR,39,1,39.503937
402596,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-11-28,2018-09-27 10:50:12.000+0000,True,EUR,40,1,39.503937
402597,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-11-28,2018-09-27 06:16:22.000+0000,True,EUR,40,1,39.503937
402598,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-11-28,2018-09-26 19:36:28.000+0000,True,EUR,39,1,39.503937
402599,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-11-17,2018-09-27 10:50:12.000+0000,True,EUR,40,1,39.503937
402600,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-11-17,2018-09-27 06:16:22.000+0000,True,EUR,40,1,39.503937
402601,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-11-17,2018-09-26 19:36:28.000+0000,True,EUR,39,1,39.503937
402602,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-09-07,2018-09-27 10:50:12.000+0000,True,EUR,39,1,39.503937
402603,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-09-07,2018-09-26 19:36:28.000+0000,True,EUR,39,1,39.503937
402604,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-10-07,2018-09-27 10:50:12.000+0000,True,EUR,39,1,39.503937
402605,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-10-07,2018-09-27 06:16:22.000+0000,True,EUR,39,1,39.503937
402606,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-10-07,2018-09-26 19:36:28.000+0000,True,EUR,39,1,39.503937
402607,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-11-08,2018-09-27 10:50:12.000+0000,True,EUR,40,1,39.503937
402608,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-11-08,2018-09-27 06:16:22.000+0000,True,EUR,40,1,39.503937
402609,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-11-08,2018-09-26 19:36:28.000+0000,True,EUR,39,1,39.503937
402610,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-10-16,2018-09-27 10:50:12.000+0000,True,EUR,40,1,39.503937
402611,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-10-16,2018-09-27 06:16:22.000+0000,True,EUR,40,1,39.503937
402612,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-10-16,2018-09-26 19:36:28.000+0000,True,EUR,39,1,39.503937
402613,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-09-10,2018-09-27 10:50:12.000+0000,True,EUR,39,1,39.503937
402614,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-09-10,2018-09-27 06:16:22.000+0000,True,EUR,39,1,39.503937
402615,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,...,False,1.0,1.0,2018-09-10,2018-09-26 19:36:28.000+0000,True,EUR,39,1,39.503937

In [10]:
from sklearn.model_selection import train_test_split
x = df[["person_capacity", "beds","bedrooms", "bathrooms"]]
y = df["local_price_y"]
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=42,test_size=0.30)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((281831, 4), (281831,), (120785, 4), (120785,))

In [11]:
from sklearn import linear_model
lm = linear_model.LinearRegression()
model = lm.fit(X_train, y_train)
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
model.score(X_test, y_test)

0.3950869994785118

In [13]:
model.coef_,model.intercept_

(array([ 35.51767437, -24.86993296,  26.4869954 ,  96.58186712]),
 -41.70211009133797)

In [14]:
prediction = model.predict(X_test)
prediction

array([175.31464644, 127.53216822, 259.12325438, ..., 147.2105886 ,
       164.66690503, 101.04517282])

In [15]:
from sklearn.metrics import mean_squared_error 
mean_squared_error(y_test, prediction)

20614.618520039745

In [21]:
#analyser le code ci-dessous 
import scipy
import numpy as np
Y_pred = model.predict(X_train)
n = X_train.shape[0]
p = 4
residuals = np.abs(y_train - Y_pred)
H = np.matmul(X_train, np.linalg.solve(np.dot(X_train.T, X_train), X_train.T))
std_hat = np.dot(residuals, residuals) / (n - p)
standart_residuals = np.asarray([residuals[i] / np.sqrt(std_hat * (1 - H[i, i])) for i in range(len(residuals))])
student_residuals = np.asarray([ standart_residuals[i] * np.sqrt((n - p - 1) / (n - p - standart_residuals[i]**2)) for i in range(n) ])
cook = np.asarray([ H[i, i] * student_residuals[i] / (X_train.shape[1] * (1 - H[i, i])) for i in range(n) ])

plt.figure(figsize=(20, 12))
plt.subplot(221)
plt.scatter(Y_pred, student_residuals, s=12, c="white", edgecolors="blue")
plt.plot([min(Y_pred), max(Y_pred)], [ scipy.stats.t.ppf(q=0.975, df=n-p-1), scipy.stats.t.ppf(q=0.975, df=n-p-1)], color="green", alpha=0.6, label="Quantile de Student")
plt.title("Analyse de l’homoscédasticité")
plt.xlabel("Prédictions $\hat{y}_i$")
plt.ylabel("Résidus studentisés $|t_i^*|$")
plt.legend()

MemoryError: Unable to allocate 592. GiB for an array with shape (281831, 281831) and data type float64